/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IROUTER,
  IROUTERInterface,
} from "../../../../contracts/Interfaces/IThorchainRouter.sol/IROUTER";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "depositWithExpiry",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IROUTER__factory {
  static readonly abi = _abi;
  static createInterface(): IROUTERInterface {
    return new utils.Interface(_abi) as IROUTERInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IROUTER {
    return new Contract(address, _abi, signerOrProvider) as IROUTER;
  }
}
