/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testerc20TokenSol from "./TESTERC20_TOKEN.sol";
export type { testerc20TokenSol };
import type * as thorChainRouterSol from "./THORChain_Router.sol";
export type { thorChainRouterSol };
export type { NetworkNationSplit } from "./NetworkNationSplit";
